eureka_hostname: service-registry

service_hostname: user-communication-service

# Test environment
#mongodb_hostname: auth-db
#mongodb_database_name: testAuthDB

# Eureka properties 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka_hostname}:8761/eureka
  instance:
    hostname: ${service_hostname}

# Server properties
server:
  port: 8096

# Application properties
spring:
  application:
    name: USER-COMMUNICATION-SERVICE
# Mail properties
  mail:
    host: smtp.gmail.com
    password: ytudiruluupiwlle
    port: 587
    properties:
      mail:
        smtp:
          auto: true
          starttls:
            enable: true
    username: cloudstoreaggregation@gmail.com
  config:
    import: optional:settings.yml
  profiles:
    active: standalone
