# Eureka properties 
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://service-registry:8761/eureka
  instance:
    hostname: localhost

# Server properties
server:
  port: 8080

# Application properties
spring:
  application:
    name: USER-COMMUNICATION-SERVICE
# Mail properties
  mail:
    host: smtp.gmail.com
    password: ytudiruluupiwlle
    port: 587
    properties:
      mail:
        smtp:
          auto: true
          starttls:
            enable: true
    username: cloudstoreaggregation@gmail.com
